name: Deploy and install service
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: dependencies
      working-directory: SuricataToASFF
      run: dotnet restore
    - name: build
      run: | 
            dotnet build SuricataToASFF.csproj --configuration Development
            dotnet publish SuricataToASFF.csproj -o ./staging/app /p:EnvironmentName=Production
    - name: copy executable
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "./staging/app/SuricataToASFF"
        target: "/home/ubuntu"
    - name: copy service file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "./SuricataToASFF.service"
        target: "/home/ubuntu"
    - name: remote ssh command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
                sudo -i
                cd ../../home/ubuntu
                cp SuricataTOASFF.service ../../etc/systemd/system/ 
                cp SuricataToASFF ../../root/SuricataToASFF
                sudo systemctl daemon-reload
                sudo systemctl status SuricataToASFF
                sudo systemctl start SuricataToASFF.service
                ./tmNIDS
                sudo systemctl status SuricataToASFF
